<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ../okica-card/public/card.glb -t -p --transform
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Plane_1: THREE.Mesh;
			Plane_2: THREE.Mesh;
		};
		materials: {
			Front: THREE.MeshStandardMaterial;
			Back: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/card.glb', { useDraco: true });

	const component = forwardEventHandlers();

	const center = (ref: THREE.Mesh) => {
		ref.geometry.computeBoundingBox();
		const max = ref.geometry.boundingBox?.max?.z || 0;
		const min = ref.geometry.boundingBox?.min?.z || 0;
		const center = (max + min) / 2;
		ref.geometry.translate(0, 0, -center);
	};

	let loaded = false;
	export const load = () => {
		loaded = true;
	};
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group
			rotation={[Math.PI / 2, 0, 0]}
			on:create={async ({ ref }) => {
				gltf.materials.Front.roughness = 0.3; // Make the front material more shiny
			}}
		>
			<T.Mesh
				on:create={({ ref }) => center(ref)}
				geometry={gltf.nodes.Plane_1.geometry}
				material={loaded ? gltf.materials.Front : gltf.materials.Back}
			/>
			<T.Mesh
				on:create={({ ref }) => center(ref)}
				geometry={gltf.nodes.Plane_2.geometry}
				material={gltf.materials.Back}
			/>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
